### ISSUE TITLE
Node16 Deprecation

### ISSUE THREAD

**Issue by kinano** [docker/setup-qemu-action#100]
Node16 will be deprecated on 09/11/2023 ([link](https://nodejs.org/en/blog/announcements/nodejs16-eol)). 

Node 16 is used by the action at the moment according to the source code: https://github.com/docker/setup-qemu-action/blob/4e6079cccbce8813e8e004099e0182f796e69345/action.yml#L23-L24

Is there a plan to release a node version update soon?

**Comment by crazy-max** [comment]
Same as https://github.com/docker/login-action/pull/590#discussion_r1315431040

> Node16 will be deprecated on 09/11/2023 ([link](https://nodejs.org/en/blog/announcements/nodejs16-eol)).

Also EOL does not mean it will go away. Same with Node 12, it was available on GH runners more than a year after EOL (until Aug 10, 2023: https://github.com/actions/runner/commit/9eb4b967132cf1575646d1f29af146a5d81de71f).

**Comment by crazy-max** [comment]
https://github.com/docker/setup-buildx-action/releases/tag/v3.0.0
