### ISSUE TITLE
Cannot support faccessat system call, image switching required

### ISSUE THREAD

**Issue by yxing-xyz** [docker/setup-qemu-action#159]
### Description

When I was building an image using buildx, I found that the system call for faccesat was not supported. After searching, I discovered that the qemu version of the image was 2 years ago and needed to switch the binfmt image from latest to master

**Comment by crazy-max** [comment]
`latest` is not set for binfmt image because https://github.com/tonistiigi/binfmt/pull/120#issuecomment-1710586120 needs to be investigated first.

**Comment by yxing-xyz** [comment]
> `latest`没有为 binfmt 图像设置，因为需要先调查[tonistiigi/binfmt#120 (注释) 。](https://github.com/tonistiigi/binfmt/pull/120#issuecomment-1710586120)

OK, I understand.
