### ISSUE TITLE
Performance - builds are very slow with QEMU

### ISSUE THREAD

**Issue by samuelcolvin** [docker/setup-qemu-action#22]
### Behaviour

Thank you so much for this action, with it I was able to build [pydantic](https://github.com/samuelcolvin/pydantic) for aarch64 with minimal code changes see https://github.com/samuelcolvin/pydantic/pull/2358

The problem is that build time as increased enormously for the step in question from 9 minutes to 69 minutes.

I realise that this is not the fault of this action, but I'd love to understand if this is expected behaviour and whether there's anything we might be able to do to speed up these builds?

I'd love to provide compiled binaries for more architectures using this technique, but the build time increase described above is significant, it would be great if there was a way to "have my cake and eat it".

### Configuration

* Repository URL (if public): https://github.com/samuelcolvin/pydantic
* Pull request: https://github.com/samuelcolvin/pydantic/pull/2358
* Build URL (if public): https://github.com/samuelcolvin/pydantic/pull/2358/checks?check_run_id=1893809664

Workflow: 

https://github.com/samuelcolvin/pydantic/blob/543d12160800d69eae40db08fb233c58dba43607/.github/workflows/ci.yml#L224-L242

**Comment by samuelcolvin** [comment]
Turns out changing `platform` from `all` to `arm64` reduced build time for me from ~69mins to ~37mins. Which is a great start.

Still anymore advice would be much appreciated.

**Comment by samuelcolvin** [comment]
bump. Anyone have any feedback on this?

**Comment by crazy-max** [comment]
@samuelcolvin Don't think that's an issue with QEMU but wheel for aarch64. See joerick/cibuildwheel#598.

**Comment by samuelcolvin** [comment]
Thank you so much.

**Comment by Dhruv-Garg79** [comment]
Is there any update on this?
I am facing the same issue, build is taking `35 mins` when building for arm64 using this plugin, otherwise it takes only 2 mins.
