### ISSUE TITLE
Usage of tonistiigi/binfmt as opposed to linuxkit/binfmt/

### ISSUE THREAD

**Issue by andrewhibbert** [docker/setup-qemu-action#79]
HI,

I'm wandering why the tonistiigi/binfmt image is used for qemu emulators as opposed to linuxkit/binfmt?

Thanks

**Comment by crazy-max** [comment]
I guess you mean https://hub.docker.com/r/linuxkit/binfmt. Looking at the source code https://github.com/linuxkit/linuxkit/tree/master/pkg/binfmt, this one lacks of support for install and uninstall flags necessary for this action and also does not support extra archs provided by @tonistiigi image: https://github.com/tonistiigi/binfmt/blob/82a943b9dfac2a5b1a565a2320327180b8dd0ba2/cmd/binfmt/config.go#L22-L68
