### ISSUE TITLE
binfmt 503 on docker pull

### ISSUE THREAD

**Issue by orcutt989** [docker/setup-qemu-action#94]
#### Steps to reproduce this issue

```
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
```

#### Expected behaviour

> No errors

#### Actual behaviour

> Run docker/setup-qemu-action@v2
  with:
    image: tonistiigi/binfmt:latest
    platforms: all
Docker info
  /usr/bin/docker version
  Client: Docker Engine - Community
   Version:           [2](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:2)4.0.5
   API version:       1.4[3](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:3)
   Go version:        go1.20.6
   Git commit:        ced0996
   Built:             Fri Jul 21 20:35:18 2023
   OS/Arch:           linux/amd6[4](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:4)
   Context:           default
  
  > Server: Docker Engine - Community
   Engine:
    Version:          24.0.[5](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:6)
    API version:      1.43 (minimum version 1.12)
    Go version:       go1.20.[6](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:7)
    Git commit:       a61e2b4
    Built:            Fri Jul 21 20:35:18 2023
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.6.22
    GitCommit:        8165feabfdfe38c65b599c4993d22[7](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:8)328c231fca
   runc:
    Version:          1.1.8
    GitCommit:        v1.1.8-0-g82f18fe
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
  /usr/bin/docker info
  Client: Docker Engine - Community
   Version:    24.0.5
   Context:    default
   Debug Mode: false
   Plugins:
    buildx: Docker Buildx (Docker Inc.)
      Version:  v0.11.2
      Path:     /usr/libexec/docker/cli-plugins/docker-buildx
    compose: Docker Compose (Docker Inc.)
      Version:  v2.20.3
      Path:     /usr/libexec/docker/cli-plugins/docker-compose
  
  > Server:
   Containers: 1
    Running: 1
    Paused: 0
    Stopped: 0
   Images: 17
   Server Version: 24.0.5
   Storage Driver: overlay2
    Backing Filesystem: extfs
    Supports d_type: true
    Using metacopy: false
    Native Overlay Diff: false
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: cgroupfs
   Cgroup Version: 2
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
   Swarm: inactive
   Runtimes: io.containerd.runc.v2 runc
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: [8](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:9)165feabfdfe38c65b5[9](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:10)9c4993d227328c231fca
   runc version: v1.1.8-0-g82f18fe
   init version: de40ad0
   Security Options:
    apparmor
    seccomp
     Profile: builtin
    cgroupns
   Kernel Version: 5.15.0-[10](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:11)41-azure
   Operating System: Ubuntu 22.04.3 LTS
   OSType: linux
   Architecture: x86_64
   CPUs: 2
   Total Memory: 6.769GiB
   Name: fv-az251-584
   ID: a4df3d93-b1a6-4b69-9304-6e279d8717a5
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Username: githubactions
   Experimental: false
   Insecure Registries:
    [12](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:13)7.0.0.0/8
   Live Restore Enabled: false
  
> Pulling binfmt Docker image
  /usr/bin/docker pull tonistiigi/binfmt:latest
  Error response from daemon: Head "https://registry-1.docker.io/v2/tonistiigi/binfmt/manifests/latest": received unexpected HTTP status: [50](https://github.com/oxheadalpha/tezos-k8s/actions/runs/5979116759/job/16222565679?pr=598#step:4:51)3 Service Unavailable
Error: The process '/usr/bin/docker' failed with exit code 1

### Additional Info

Looks like its pulling https://registry-1.docker.io/v2/tonistiigi/binfmt/manifests/latest which gives me a `{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"tonistiigi/binfmt","Action":"pull"}]}]}`

**Comment by NicolasCARPi** [comment]
I have a slightly different error:

~~~
 /usr/bin/docker pull tonistiigi/binfmt:latest
  error during connect: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.43/images/create?fromImage=tonistiigi%2Fbinfmt&tag=latest": EOF
Error: The process '/usr/bin/docker' failed with exit code 1
~~~

Run: https://github.com/elabftw/elabimg/actions/runs/6007012754/job/16292461919

**Comment by crazy-max** [comment]
`HTTP status: 503 Service Unavailable` means the registry is currently unavailable and might have transient issues so the binfmt image can't be pulled. Please try again and if the error still persist you can report at https://github.com/docker/hub-feedback/issues. Thanks.

**Comment by orcutt989** [comment]
Is it possible the image namespace changed? If you click https://registry-1.docker.io/v2/tonistiigi/binfmt/manifests/latest  what do you see? I get an "unauthorized".

**Comment by orcutt989** [comment]
Nevermind! Its fine now.
